### ISSUE TITLE
question

### ISSUE THREAD

**Issue by timchenxiaoyu** [AgilData/mesos-docker-tutorial#3]
[root@localhost mesos-docker-tutorial-master]#  java -classpath target/cf-tutorial-mesos-docker-1.0-SNAPSHOT-jar-with-dependencies.jar com.codefutures.tutorial.mesos.docker.ExampleFramework 127.0.0.1:5050 fedora/apache 2
Failed to load native Mesos library from /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Exception in thread "main" java.lang.UnsatisfiedLinkError: no mesos in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:54)
    at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:79)
    at org.apache.mesos.MesosSchedulerDriver.<clinit>(MesosSchedulerDriver.java:61)
    at com.codefutures.tutorial.mesos.docker.ExampleFramework.main(ExampleFramework.java:106)

**Comment by lesblueleaves** [comment]
the same issue as the upstair, got solution?

**Comment by truthwzl** [comment]
export MESOS_NATIVE_JAVA_LIBRARY=path to libmesos.so.
http://spark.apache.org/docs/latest/running-on-mesos.html
